---
title: "PTT"
author: "Annie Chen"
date: "2019/7/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(jiebaR)
library(tmcn)
library(tibble)
library(dplyr)
ptt.url <- "https://www.ptt.cc"
gossiping.url <- str_c(ptt.url, "/bbs/Gossiping")
gossiping.pre.session <- html_session(url = gossiping.url)
gossiping.pre.session
full_page <- read_html(gossiping.url)
full_page
form.18 <- gossiping.pre.session %>%
	html_node("form")%>%
	html_form()
form.18
gossiping.session <- submit_form(
	 session = gossiping.pre.session,
	 form = form.18,
	 submit = "yes"
)
gossiping.session
page.latest <- gossiping.session %>%
	html_node(".wide:nth-child(2)") %>%
	html_attr("href") %>%
	str_extract("[0-9]+")%>%
	as.numeric()
page.latest
links.article <- NULL
page.number <- 100
page.index <- page.latest
page.processed <- 0
for (page.index in page.latest : (page.latest - page.number)){
	page.processed <- page.processed + 1
	link <- str_c(gossiping.url, "/index", page.index, ".html")
	cat("fetching link", page.processed, "/", page.number + 1, "...", link, "\n")
	links.article <- c(links.article,
		gossiping.session %>%
		jump_to(link) %>%
		html_nodes(".title a") %>%
		html_attr("href"))}
links.article <- unique(links.article)
titles = NULL
texts = NULL
time.stamp = NULL
pushes = NULL
progress <- 0
for (temp.link in links.article) {
		progress <- progress + 1
		article.link <- paste0(ptt.url, temp.link)
		cat('processing article', progress, '/', length(links.article), '...')
		print(article.link)
		titles <- c(titles, 
			gossiping.session %>%
			jump_to(article.link) %>%
			html_nodes(".article-metaline-right+ .article-metaline .article-meta-value") %>%
			html_text() %>%
			str_c(collapse = "")
		)
		texts <- c(texts,
			gossiping.session %>%
			jump_to(article.link) %>%
			html_nodes(xpath = '//*[@id="main-content"]/text()') %>%
			html_text() %>%
			str_c(collapse = "")
		)
		time.stamp <- c(time.stamp,
			gossiping.session %>%
			jump_to(article.link) %>%
			html_nodes(".article-metaline+ .article-metaline .article-meta-value") %>%
			html_text() %>%
			str_c(collapse = "")
		)
		pushes <-  c(pushes,
			gossiping.session %>%
			jump_to(article.link) %>%
			html_nodes(".push-tag") %>%
			html_text() %>%
			str_c(collapse = "")
		)
	}
tab <- data.frame(
		title = titles,
		text =  texts,
		time = time.stamp,
		push_raw = pushes
	)
```