---
title: "MarriageAndDivorce"
author: "Annie Chen"
date: "2019/7/11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

參考資料:\r\n
https://www.ris.gov.tw/app/portal/346\r\n

結婚及離婚\r\n

(01結婚對數及粗結婚率(按登記)(36) [xls] [ods])\r\n
(07離婚對數及粗離婚率(按登記)(36) [xls] [ods])\r\n

根據內政部最新統計，今年1月有1萬4314對新人結婚，結婚率千分之7.15，由於農曆年前原本就是結婚旺季，若與去年同月相較，仍減少54對。今年1月也有4384對夫妻離婚，離婚率千分之2.19，比去年同期增加612對，離婚率大幅提高16.22％。

對於結婚少，離婚多的現象，兩性學者何春蕤表示，根本原因是社會變遷，人與人相互容忍度越來越低，彼此和樂相處變得不太容易。結婚的目的既然不能得到更多好處，反而變成麻煩事，年輕人自然就感到遲疑，甚至裹足不前。

```{r rate}
library(dplyr)
library(readxl)
divorceRate <- read_excel("D:/download/Rclass/divorceRate.xls")
marriageRate <- read_excel("D:/download/Rclass/marriageRate.xls")
general=merge(marriageRate,divorceRate,by="year")
 general
```

##結婚率與離婚率折線圖

```{r LineChart}
library(dplyr)
library(readxl)
library(ggplot2)
data1<-read_excel("D:/Annie/Documents/GitHub/GitHubForRClass/RClassRepository/Week2/20190715/test/rateTest.xlsx")

ggplot(data=data1,aes(x=year,y=rate,group=supp))+geom_line(linetype="dashed",color="skyblue",size=1.2)+geom_point(color="pink",size=1.5)

p<-ggplot(data1, aes(x=year, y=rate, group=supp)) +
  geom_line(aes(color=supp))+
  geom_point(aes(color=supp))

# Use custom color palettes
p+scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9"))
# Use brewer color palettes
p+scale_color_brewer(palette="Dark2")
# Use grey scale
p + scale_color_grey() + theme_classic()

p
```

##結婚率的長條圖

```{r BarChart4M}
data2<-read_excel("D:/download/Rclass/marriageRate.xls")
data4Marriage<-select(data2,"year","marriageRate")
ggplot(data=data4Marriage,aes(x=year,y=marriageRate,fill=year))+geom_bar(stat="identity")
```

##離婚率的長條圖
```{r BarChart}
data3<-read_excel("D:/download/Rclass/divorceRate.xls")
data4Divorce<-select(data3,"year","divorceRate")
ggplot(data=data4Divorce,aes(x=year,y=divorceRate,fill=year))+geom_bar(stat="identity")
```

